DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS requests;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(256) NOT NULL,
  email VARCHAR(512) NOT NULL UNIQUE
  --CONSTRAINT pk_user PRIMARY KEY (id),
  --CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description VARCHAR(1024) NOT NULL,
  requestor_id INT NOT NULL,
  created TIMESTAMP NOT NULL,
  FOREIGN KEY (requestor_id) REFERENCES users(id) ON DELETE CASCADE
  --created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  --CONSTRAINT pk_request PRIMARY KEY (id),
  --CONSTRAINT fk_request_requestor FOREIGN KEY (requestor_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(256) NOT NULL,
  description VARCHAR(1024),
  is_available BOOLEAN NOT NULL,
  owner_id INTEGER NOT NULL,
  request_id INTEGER NULL,
  FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (request_id) REFERENCES requests(id) ON DELETE SET NULL
  --CONSTRAINT pk_item PRIMARY KEY (id),
  --CONSTRAINT fk_item_owner FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE,
  --CONSTRAINT fk_item_request FOREIGN KEY (request_id) REFERENCES requests(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS bookings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  --start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  --end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  start_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP NOT NULL,
  item_id INTEGER NOT NULL,
  booker_id INTEGER NOT NULL,
  status VARCHAR(24) NOT NULL,
  FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE,
  FOREIGN KEY (booker_id) REFERENCES users(id) ON DELETE CASCADE
  --CONSTRAINT pk_booking PRIMARY KEY (id),
  --CONSTRAINT fk_booking_item FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE,
  --CONSTRAINT fk_booking_booker FOREIGN KEY (booker_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text VARCHAR(2048) NOT NULL,
  item_id INTEGER NOT NULL,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL,
  FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE,
  FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE
  --created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  --CONSTRAINT pk_comment PRIMARY KEY (id),
  --CONSTRAINT fk_comment_item FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE,
  --CONSTRAINT fk_comment_author FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Создание индексов для ускорения поиска
CREATE INDEX idx_items_owner_id ON items(owner_id);
CREATE INDEX idx_items_request_id ON items(request_id);
CREATE INDEX idx_bookings_item_id ON bookings(item_id);
CREATE INDEX idx_bookings_booker_id ON bookings(booker_id);
CREATE INDEX idx_comments_item_id ON comments(item_id);
CREATE INDEX idx_comments_author_id ON comments(author_id);
CREATE INDEX idx_requests_requestor_id ON requests(requestor_id);
--CREATE INDEX IF NOT EXISTS idx_items_owner_id ON items(owner_id);
--CREATE INDEX IF NOT EXISTS idx_items_request_id ON items(request_id);
--CREATE INDEX IF NOT EXISTS idx_bookings_item_id ON bookings(item_id);
--CREATE INDEX IF NOT EXISTS idx_bookings_booker_id ON bookings(booker_id);
--CREATE INDEX IF NOT EXISTS idx_comments_item_id ON comments(item_id);
--CREATE INDEX IF NOT EXISTS idx_comments_author_id ON comments(author_id);
--CREATE INDEX IF NOT EXISTS idx_requests_requestor_id ON requests(requestor_id);